# Generated by Django 3.2.9 on 2022-05-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0002_auto_20220514_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_description',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_nickname',
        ),
    ]
