# Generated by Django 3.2.9 on 2022-05-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0002_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
