# Generated by Django 3.2.9 on 2022-05-01 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0002_userbookrelation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBookRelation',
        ),
    ]
