# Generated by Django 3.2.9 on 2022-05-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0003_auto_20220519_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
